buildscript {
    ext.kotlin_version = '2.0.21'  // Kotlin 1.9.22 pra compatibilidade total
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'  // AGP 8.2.2
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
