// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXTy3vBt1BD2DdZlSjGRq6RcsGJPwUFo',
    appId: '1:491950036407:android:1b5e5259756c7051034432',
    messagingSenderId: '491950036407',
    projectId: 'to-chegando-motoboy-24b4a',
    databaseURL: 'https://to-chegando-motoboy-24b4a-default-rtdb.firebaseio.com',
    storageBucket: 'to-chegando-motoboy-24b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWw5x1u9KLFoxIJaMWV0Sh_TnlhmZKQNc',
    appId: '1:491950036407:ios:41fe4f24133e3b76034432',
    messagingSenderId: '491950036407',
    projectId: 'to-chegando-motoboy-24b4a',
    databaseURL: 'https://to-chegando-motoboy-24b4a-default-rtdb.firebaseio.com',
    storageBucket: 'to-chegando-motoboy-24b4a.firebasestorage.app',
    androidClientId: '491950036407-1d7k624v0f0jdrrbat4e13f4kkpjolpd.apps.googleusercontent.com',
    iosClientId: '491950036407-16ftavdnpnenbb1917dc2h50comebr6q.apps.googleusercontent.com',
    iosBundleId: 'com.tochegando.motoboy',
  );

}